[build]
  command = "bun run build"
  publish = "dist"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
